### ISSUE TITLE
README description missing

### ISSUE THREAD

**Issue by gevera** [atomvm/exatomvm#4]
As per https://www.atomvm.net/doc/master/getting-started-guide.html#elixir-tooling 

Need description of how to write elixir code and run it on esp32 via AtomVM

**Comment by fadushin** [comment]
Thanks @gevera .  Definitely true.  Can you have a look at https://github.com/atomvm/ExAtomVM/pull/1/files and see if that helps?

**Comment by gevera** [comment]
That works. Thanks
